import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google';
import "./globals.css";
import Footer from "@/components/ui/footer";
import Navbar from "@/components/Navbar";

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-dm-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmSans.variable}>
        <Navbar/>
        {children}

        <Footer/>
      </body>
    </html>
  );
}
